<div class="container-fluid">
<p>
    <h4>Bienvenue dans le projet ZFPrototype4 (ZFP4)</h4><br>
    Ce projet est un prototype d'application de type CRUD (acronyme de "Create, Read, Update, Delete") destiné à servir de modèle, de base de travail, pour le développement d'applications "métiers".<br>
    J'avais développé ce projet, il y a quelques années, en pensant particulièrement aux développeurs IBM i, car ZF1 est à mon avis l'un des frameworks PHP les mieux adaptés pour le développement de 
    projets destinés à la plateforme IBM i.<br><br>
    Pour la petite histoire, j'avais laissé ce projet de côté, après l'annonce de l'abandon de ZF 1 par son éditeur (Zend), au profit du projet ZF 2, 
    très différent donc incompatible avec la version 1 (une version 2 qui à mon sens n'a jamais tenu ses promesses).<br>
    J'ai réactivé ZFP4 après avoir découvert que le projet ZF 1 était remis sur les rails par une communauté active et motivée, sous le nom 
    de <a href="https://github.com/Shardj/zf1-future" target="_blank">"ZF1-Future"</a>.<br><br>
    Ce projet est donc construit sur une base de ZF 1, ou plus exactement sur la version 1.21 de ZF1-Future.<br>
    ZF1-Future ayant été révisé pour PHP8, j'ai vérifié l'ensemble du code de ZFP4 pour m'assurer qu'il était bien compatible avec PHP8 et ZF1-Future. <br>
    
    J'en ai profité pour éliminer quelques fonctionnalités obsolètes, et pour moderniser le design en m'appuyant sur le framework CSS 
    <a href="https://getbootstrap.com/docs/4.6/getting-started/introduction/" target="_blank">Booststrap 4</a>. <br><br>
    Cette révision de ZFP4 m'a amené à appliquer quelques patchs sur ZF1-Future, patchs que j'ai listés dans le README du projet.<br>

    Pourquoi ce projet porte-t-il le numéro "4" ? Parce que ce projet a connu plusieurs évolutions. Cette version 4 est de loin la plus aboutie, et la première que je publie en open-source.<br><br>

    Prenez ZFP4 pour ce qu'il est. Ce n'est pas un projet parfait, prêt à l'emploi, c'est un exemple conçu pour vous familiariser avec ZF1, que vous pouvez adapter à votre convenance, et à vos propres spécificités "métier".

</p>
</div>