<?php
$db = Zend_Registry::get('db');
/*
 * on privilégie ici l'utilisation d'un curseur SQL, de préférence à FetchAll,
 * car on risque de traiter de gros volumes, et un FetchAll pourrait entraîner
 * un dépassement de capacité au niveau du serveur
 */
$stmt = $db->query($this->sql);
$export_xls_nbl_max = Zend_Registry::get('export_xls_nbl_max');  

// code sensé forcer l'ouverture de la page dans une autre page du navigateur (ne fonctionne
// pas pour l'instant)
//<script type="text/javascript" src="<body onLoad="javascript:window.print(); document.getElementById('frmListe').submit();">"></script>
?><table>
    <tr>
        <th width="5%">Code</th>
        <th width="10%">Nom et prénom</th>
    </tr>
    <?php
    $compteur_lignes = 0;
    while ($data = $stmt->fetch()) {
    ?>
        <tr>
            <td width="5%"><?php echo $this->escape($data['code']); ?></td>
            <td width="10%"><?php echo $this->escape($data['libelle']); ?></td>
        </tr>
    <?php
        $compteur_lignes++;
        if ($compteur_lignes > $export_xls_nbl_max) {
            break;
        }
    }
    ?>
</table>
<?php
    echo '<br/>' . PHP_EOL;
