<?php
echo '<br/>';

$registry = Zend_Registry::getInstance(); 
if ($registry->get('auth_create') === true) {
    echo '<div class="div_block">' . PHP_EOL;
    echo '&raquo;';
    echo '<a class="btn btn-primary btn-sm" href="' . $this->url(array(
        'controller' => $this->mvc_controller_name,
        'action' => 'add')) . '">';
    echo'Créer une personne';
    echo '</a>';
    echo '</div>';
}

echo '<fieldset>';
echo'<legend>Crit&egrave;res de s&eacute;lection</legend>';
echo '<div>' . PHP_EOL;
echo $this->form;
echo '<div>' . PHP_EOL;
echo '</fieldset>' . PHP_EOL;
echo '<br/>' . PHP_EOL;

$pagination = $this->paginator . PHP_EOL;

?>
<table class="table table-striped table-sm table-bordered" >
    <thead class="thead-dark">
        <tr class="header-row">
        <th><a href="?column_name=code">Code</a></th>
        <th><a href="?column_name=libelle">Nom et prénom</a></th>
        <th>&nbsp;</th>
        <?php if ($registry->get('auth_update') === true) {
        ?>
            <th>&nbsp;</th>
        <?php } ?>
        <?php if ($registry->get('auth_delete') === true) {
        ?>
            <th>&nbsp;</th>
        <?php } ?>        
        </tr>
  </thead>
  <tbody>
    <?php
        $styles_tab = array('even-row', 'odd-row') ;
        $lastRowNumber = 0 ;
        foreach ($this->paginator as $prov) :
        $lastRowNumber++;
    ?><tr>
            <td><?php echo $this->escape($prov->code).'&nbsp;'; ?></td>
            <td><?php echo $this->escape($prov->libelle).'&nbsp;'; ?></td>
            <td align="center"><a class="btn btn-primary btn-sm" href="<?php
        echo $this->url(array(
            'controller' => $this->mvc_controller_name,
            'action' => 'display',
            'id' => $prov->id
        ));
    ?>">Afficher</a>&nbsp;
        </td>
<?php if ($registry->get('auth_update') === true) { ?>
                <td align="center"><a class="btn btn-success btn-sm" href="<?php
                echo $this->url(array(
                    'controller' => $this->mvc_controller_name,
                    'action' => 'edit',
                    'id' => $prov->id
                ));
?>">Modifier</a>&nbsp;
        </td>
        <?php } ?>
<?php if ($registry->get('auth_delete') === true) { ?>
                <td align="center"><a class="btn btn-danger btn-sm" href="<?php
                echo $this->url(array(
                    'controller' => $this->mvc_controller_name,
                    'action' => 'delete',
                    'id' => $prov->id
                ));
?>">Supprimer</a>&nbsp;
        </td>
<?php } ?>
        </tr>
<?php endforeach; ?>
       </tbody>
      </table>
<?php
            echo '<br/>' . PHP_EOL;
            echo $pagination;
