<?php

//$registry = Zend_Registry::getInstance();
//$db = $registry::get('db');
//$stmt = $db->query($this->persql);

echo '<fieldset>';
echo'<legend>Modification</legend>';
echo '<br/>'.PHP_EOL ;
echo $this->form ;
echo '<br/>'.PHP_EOL ;
echo '</fieldset>'.PHP_EOL;

?>
<script>
function homogeneise_form () {
    let items = document.querySelectorAll('dt')
    for (let i=0, imax=items.length; i<imax; i++) {
      items[i].classList.add('row');
    }
    items = document.querySelectorAll('dd')
    for (let i=0, imax=items.length; i<imax; i++) {
      items[i].classList.add('row');
    }
} 
</script>
<script src="../../../js/components/Pagination.js" ></script>    
<script src="../../../js/components/personnesModule.js" ></script>    

<!-- FENETRE MODALE "LISTE DES PERSONNES -->
<div style="visibility:hidden" >
  <span data-hook="personne_id">&nbsp;</span>
  <input id="libelle_personne_id" type="text" class="form-control col-sm-6" value="" disabled data-hook="personne_id" />
  <span data-hook="personne_id">&nbsp;</span>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modaleRechClients" data-hook="personne_id" >
    Recherche personnes
  </button>
  <span data-hook="personne_id">&nbsp;</span>
</div>
<!-- Modal -->
<div class="modal fade" id="modaleRechClients" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="modaleRechClientsLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modaleRechClientsLabel">Fenêtre de recherche sur les personnes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label for="filter_personne_id">Recherche</label>
          <input type="text" class="form-control" id="filter_personne_id" aria-describedby="Name filter">
        </div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">&nbsp;</th>
              <th scope="col">Code</th>
              <th scope="col">Nom et prénom</th>
            </tr>
          </thead>
          <tbody data-formlink="personne_id" ></tbody>
        </table>
        <div data-barnav="personne_id"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  // Homonégéïsation de la présentation des labels et champs de formulaire
  js_hooks.push("homogeneise_form()");
  // activation de la fonction de recherche de personnes (via fenêtre modale)
  js_hooks.push("personnesModule.init('modaleRechClients', 'personne_id')");

</script>